### ISSUE TITLE
Deploy front-end to gh-pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1218]
The badgeyay project deploys the ember frontend to gh-pages. Can we do the same here, e.g. using this https://www.npmjs.com/package/ember-cli-deploy-github-pages ?

**Comment by mayank8318** [comment]
@bhaveshAn @srv-twry  @Kreijstal @pradeepgangwar @niranjan94 @SaptakS I was planning to write a script which would contain the lines from the installation guide. This would run in the after-script section of Travis and I will include a check so that only commits to development are published.
What are your views on this? Should I go ahead with this approach?

**Comment by niranjan94** [comment]
@mayank8318 sure go ahead
