### ISSUE TITLE
Add event sub topic button should be disabled until a topic is selected.

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1325]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17252805/41919198-34aa398a-795e-11e8-8e50-bb45ca462e53.png)
If no topic is selected, then adding an event sub topic is not possible and adding it anyway results in an unexpected error notification.

**Comment by mayank8318** [comment]
@CosmicCoder96 I would like to work on this. Also, I find the flow confusing because the first drop-down lets you see the sub-topics already present for various topics but when you press the `+` button the user also has to select the event topic for which he wants to add the sub-topic. Shouldn't the sub-topic be added to the topic selected in the first drop-down before pressing the `+` button?

**Comment by CosmicCoder96** [comment]
@mayank8318 I think that's because in case someone directly wants to add subtopics, without selecting the topic in the topic dropdown first. Maybe you can make it such that once the user has selected a topic, the corresponding sub topics get displayed. When the user now clicks on the add subtopics button, let the dropdown be there but make it's selected default value equal to the topic value (if topic is selected by user).

**Comment by mayank8318** [comment]
@CosmicCoder96 ok I will make it that way
