### ISSUE TITLE
Improve ui-table cell templates & response for the table

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#161]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

First version of the ui-table implementation simply added dummy data inside the cell templates. Please improve the cell templates and the response data for the table.

This includes
- Improving existing cell-templates
- Improving dummy data structure to mimic API response.
- Adding new cell-templates

I would be working on this issue. Thanks

**Comment by niranjan94** [comment]
@geekyd 

<img width="1680" alt="screen shot 2017-06-07 at 10 43 28 pm" src="https://user-images.githubusercontent.com/2404372/26891544-02762ab4-4bd3-11e7-9982-e053370a7446.png">

Main thing that should be done as a part of this is UI improvements. 

1. The search box to be right aligned. Use the search box styling provided by semantic UI. And search box should not be in contact with the table.
2. Should not be in contact with the table. Use `text muted` class.
3. Should not be in contact with the table. Hidden if only one page.
4. Same row as search. Left aligned. Hide if less than 10 entities. 

Ensure this issue is given a higher priority. Needs to be done in this milestone.

**Comment by geekyd** [comment]
@niranjan94 I will start working on this as soon as possible. We will be completing it in the milestone only.
