### ISSUE TITLE
Tickets show orders including expired orders on event dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1796]
Event dashboard should show only data from actual orders.

![screenshot from 2019-01-14 21-19-50](https://user-images.githubusercontent.com/1583873/51138754-3a81bd00-1842-11e9-95b3-ca6a01a1b8ab.png)

**Comment by shreyanshdwivedi** [comment]
I'm working on this

**Comment by uds5501** [comment]
@shreyanshdwivedi Are you working on this?

**Comment by shreyanshdwivedi** [comment]
@uds5501 yep. Sorry for the delay. Was caught up with some work
Will submit a PR soon

**Comment by uds5501** [comment]
@shreyanshdwivedi Alright sure!

**Comment by shreyanshdwivedi** [comment]
@mariobehling this issue is not reproducible on my local.
I have expired order but it is not showing on event dashboard
![screenshot_2019-02-01 all orders tickets apk19 events open event](https://user-images.githubusercontent.com/25428397/52081789-1e5f7900-25c1-11e9-8e18-1f5601cfaeeb.png)
![screenshot_2019-02-01 apk19 events open event](https://user-images.githubusercontent.com/25428397/52081794-215a6980-25c1-11e9-8e8a-7a2ae8cf688b.png)
