### ISSUE TITLE
Speakers image are broken and wrong dimensions

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-frontend#1926]
**Describe the bug**
Screenshot shows image on left has different sizing as the other two and the other images are having 404 errors

**To Reproduce**
1. Go to https://eventyay.com/e/3689bc98/speakers

**Expected behavior**
Pictures should show out without 404 and correct dimensions

**Screenshots**
![404 image](https://user-images.githubusercontent.com/11439477/51469779-17f52400-1dad-11e9-9be6-9dcccb2229ac.jpeg)

**Desktop (please complete the following information):**
Windows
Chrome 71.0.3578.98

**Comment by CosmicCoder96** [comment]
@cweitat Thanks for reporting.
Actually, the 404s are not for the images, but for microlocations of unscheduled sessions, and the uneven sized images you see, are not because of image themselves being disproportionate but due to the fact thay they were not optimized. It becomes a 40 MB+ Download if a user visits the page, hence they were in process of loadinng at the time of screenshot. This optimization issue has now been resolved by #1920
