### ISSUE TITLE
Sales page not visible

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2151]
**Describe the bug**
Sales page not visible

**Expected behavior**
Sales page should be visible

**Screenshots**
![salespage](https://user-images.githubusercontent.com/19900978/52432346-38083f80-2b30-11e9-807e-fa5d2785393d.png)

**Additional context**
I am working on this issue.

**Comment by uds5501** [comment]
@shubham3211 This looks more like a server side error, besides i think issues regarding admin sales should be left for now due to ongoing integration by @YogeshSharma0201 
![screenshot from 2019-02-07 03-13-41](https://user-images.githubusercontent.com/21087061/52442077-4b270980-2b48-11e9-91c9-eb03c64580f8.png)
