### ISSUE TITLE
Currency-Symbol not getting rendered or breaking the page

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2444]
**Describe the bug**

Correct Currency-Symbols parser on the basis of event is not getting rendered at some places extension of #2376 

**To Reproduce**

Steps to reproduce the behaviour:

1.) Admin/Sales/By Organizer , If we change the '$' to currency parser build gets broken.
2.) Admin/Sales/By Location , If we change the '$' to currency parser build gets broken.
3.) Events/View/Tickets/Discount Codes , Cell amount currency parser is not getting parsed.
4.) After introducing currency parser in Events/overview/event-tickets.hbs , fails the build.

**Expected behavior**

Currency Parser should be rendered everywhere correctly

**Comment by kushthedude** [comment]
@CosmicCoder96 just a simple suggestion why dont you guide me in solving this rather than you yourself solve this🙄

**Comment by mariobehling** [comment]
@kushthedude Thanks for finding out about the issue. People in the community are free to follow their interests. Some people like to teach others, some like to focus on solving code issues themselves and things sometimes change. Right now our focus is to make this project stable, so the next release will work and the main time of devs should go into solving issues rather than teaching others. 

There are many opportunities to learn in the FOSSASIA community. We have our blog. We share the talks of events on the Youtube channel and some people help others on chat channels. Please understand that everyone works according to her or his interests and preferences. 

Asking for guidance could be understood in a way that you expect other developers to teach you step by step how to solve an issue. While this might be possible in other communities and school, it is usually out of scope in FOSSASIA projects as we just don't have the resources to teach people how to solve issues. I hope you understand and take it as a motivation. Thank you.

**Comment by mohitm15** [comment]
@mariobehling absolutely correct sir ,😃

**Comment by kushthedude** [comment]
@mariobehling Thanks for the guide , I have read the blogs of FOSSASIA written by many dev's working on the current project ,Need to say they were really helpful in understanding the details about the project and the tech used in here and I really enjoy working with the community here . FOSSASIA is my first Open-Source organisation . I will work on other major bugs now and I am really looking forward to working with this esteemed organisation . 😄

**Comment by mohitm15** [comment]
@shreyanshdwivedi I would like to take this referenced from #2468  as its been 15 days from now and PR is pushed.

**Comment by CosmicCoder96** [comment]
@mohitm15 No, please work on a different issue. This is not ready to be worked on.

**Comment by CosmicCoder96** [comment]
Will be fixed in #3018
