### ISSUE TITLE
Create event button overflows in mobile devices

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#247]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
![19264943_1338882936194999_277566138_n](https://user-images.githubusercontent.com/12807846/27250463-546fe116-534e-11e7-825b-5fa34050bc14.jpg)

**Expected behavior:**
![screenshot from 2017-06-17 11-47-31](https://user-images.githubusercontent.com/12807846/27250687-ca2a9136-5352-11e7-9cc1-e49f4757961a.png)

Working on the fix.

**Comment by anu-007** [comment]
@geekyd I think we should redesign navbar and sidebar because there are several things that I have noticed should be changed like- 

-browse event button should be below the user's name and avatar. 
![image](https://user-images.githubusercontent.com/20153241/27250762-8ace9f4e-5354-11e7-84ba-b8f34470e576.png)

-the transition of the sidebar should be smooth

-the sidebar should appear over the content not pushing the content to the right just like the web app generated by open-event-webapp

-eventyay logo should appear in the sidebar.

please correct me if I am wrong and what are your thoughts @geekyd @utkarshnath @CosmicCoder96 @harshitagupta30 @sumedh123

**Comment by niranjan94** [comment]
The transitions are disabled because they were causing some issues with the
ember view loading.

We want a functional nav bar and side bar. And right now it's very
functional (except for the minor responsive issue) and looks pretty good
too. So redesigning it at this point when we have so many other stuff
pending is overkill.

As. For pushing, I don't see what's the advantage of over the content vs
pushing the content and why we should make a change. (ps. Pushing is the
default behavior for semantic sidebar. But it supports over too, though I
don't see why we should switch
)
