### ISSUE TITLE
Make text input fields remember previously entered data

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2500]
**Describe the bug**
Input field like email should show previously entered value for ease.

**Expected behavior**
A dropdown should be shown of previously entered values.

**Additional context**
Working on it.

**Comment by CosmicCoder96** [comment]
Input fields where ? More context please.

**Comment by prateekj117** [comment]
@CosmicCoder96 For example when entering Email.

**Comment by kushthedude** [comment]
@CosmicCoder96 I think @prateekj117 wants to refer to feature like *autocomplete* which is available in html forms ?

**Comment by CosmicCoder96** [comment]
Entering email where ? If you mean like this in general then its taken care of in production environment. It doesn't work on localhost due to unconfigured cookie-policy.
![image](https://user-images.githubusercontent.com/17252805/55679371-35ae4000-593d-11e9-90b7-629f6aba1e16.png)
If that is what you meant you may close this issue else elaborate further.

**Comment by prateekj117** [comment]
@CosmicCoder96 Yes, this is what I meant. Ok, understood.
