### ISSUE TITLE
Social Site Login is not working

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/open-event-frontend#26]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The Login with Facebook / Twitter / Google Button are not working.

**Expected behavior:**
The Buttons should initiate login with social accounts.

**Steps to reproduce:**
Ex for Facebook. You may register on https://developers.facebook.com/docs/facebook-login/web and follow the documentation

Your operating system
Windows 10

I would like to work on this feature

**Comment by niranjan94** [comment]
@AnupKumarPanwar the front is still a very new project and there are certain things that require backend changes in the open-event-orga server since we're moving towards an API centric pattern now. So, this is one of them and that's why it's still pending. I'd suggest you take a look at the already open issues. More will be opened soon.
