### ISSUE TITLE
option to cancel the order being shown in completed order

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2722]
**Describe the bug**

Currently if we have an order which has been paid for and is complete, we still get an  option to cancel the order which should not be the case

**To Reproduce**
Steps to reproduce the behaviour:
1. Complete an order which brings the net amount down to 0 (maybe with a discount code)
2. Go to Event/Tickets/Order
3. See error

**Expected behaviour**

It should not have a cancel option for a paid and completed order.

**Screenshots**

![Screenshot from 2019-04-18 16-35-52](https://user-images.githubusercontent.com/21087061/56357076-39bd4600-61f8-11e9-9127-73fdef5bc9c0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by kushthedude** [comment]
@uds5501 Why have we implemented this , A paid order can be cancelled too ?

**Comment by uds5501** [comment]
@kushthedude how do you propose to refund the money post cancellation?

**Comment by kushthedude** [comment]
@uds5501 AFAIK PayTM and Paypal both have refund API based on the payment token , And I propose to add two categories of ticket Refundable and non Refundable , Since with this PR the user cant cancel his order nor the organiser . Regarding the short term go i can agree it can work but cant be a perfect solution buddy
