### ISSUE TITLE
Event Wizard Step 1: Add Tax Info - Increase height and show all info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2798]
The tax info in the wizard step 1 ..
a) .. needs a scrollable field. Please increase the height of the field to minimize the need for scrolling.
b) Show all the tax info including company details once the field has been saved.

![Screenshot from 2019-04-25 00-19-38](https://user-images.githubusercontent.com/1583873/56676385-bd8f9a80-66f0-11e9-97bc-e6a71a9530aa.png)

![Screenshot from 2019-04-25 00-22-03](https://user-images.githubusercontent.com/1583873/56676400-c4b6a880-66f0-11e9-9fa9-1ddc9b9b9d6a.png)

**Comment by prateekj117** [comment]
@mariobehling Looking into it.

**Comment by uds5501** [comment]
@prateekj117 can i please take over while you are focusing on the network error issue?

**Comment by prateekj117** [comment]
@kushthedude I just wasted half an hour on this issue and realized later you already did a PR for it without claiming it. Even @uds5501 didn't take it up when I didn't reply for so many days. This is exactly why you always claim an issue first. And if the other person doesn't reply, then comment on it that you are taking it over due to inactivity.

**Comment by prateekj117** [comment]
@kushthedude No, don't close the PR. You must have given much more time to the issue now than me. Just comment from next time that you are taking over the issue due to inactivity.

**Comment by kushthedude** [comment]
@prateekj117 Will take care next time 😄
