### ISSUE TITLE
Replace anchor tags with link-to helpers for transition within the app.

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#282]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

currently there are many places hard coded anchor tag links are there for transition within the project they should be replaced by link-to helper as anchor tags reloads the app instead of just transitioning.

**Comment by anu-007** [comment]
I like to work on this.

**Comment by niranjan94** [comment]
Can you tell me which cases?

**Comment by niranjan94** [comment]
Because as far as I can see achor tags react the same way as `link-to` (Which are just basically anchor tags along with some _magic_ to add the `active` depending on which page the user is in) as long as the links are relative to the project and to known routes. 

There is a reason why some places don't use `link-to` helper and use a normal `a` tag along with a `href-to` instead. The `link-to` tag creates a whole new component and hence all the bindings, memory usage etc that comes along with a component is also there for every link. But `href-to` on the other hand is a simple helper and just provides a link text. Both `href-to` and `link-to` are similar is all aspects .. except for the fact that `link-to` provides automatic `active` class binding. 

But we don't need the `active` class binding at all places. So, as far as this project is concerned, anywhere you need automatic `active` class binding, use `link-to` else use a normal `a` tag along with the `href-to` helper.

**Comment by niranjan94** [comment]
@fossasia/open-event-frontend please note. 👆

**Comment by niranjan94** [comment]
> currently there are many places hard coded anchor tag links are there for transition within the project they should be replaced by link-to helper as anchor tags reloads the app instead of just transitioning.

This shouldn't be happening anywhere. But some routes related to authentication, like logout for example will cause a full page reload.

**Comment by anu-007** [comment]
@niranjan94 thanks for the clarification and I completely agreed with you, most of the places that I find out would not need `active` class binding hence closing this issue.
