### ISSUE TITLE
Session is getting created without Speaker Details

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3049]
**Describe the bug**

Session is getting created without Speaker Details

#### Steps to reproduce the behaviour:

- Try to create session without choosing any speaker

**Expected behaviour**

Throw the error

**Screenshots**

<img width="1440" alt="Screenshot 2019-06-03 at 11 38 45 AM" src="https://user-images.githubusercontent.com/44091822/58779705-5b319000-85f4-11e9-96d0-4d5a9f8c701d.png">

**Comment by uds5501** [comment]
@kushthedude This is an intended feature.

**Comment by kushthedude** [comment]
@uds5501 Can you provide more details?

**Comment by uds5501** [comment]
@kushthedude AFAIK, an organiser can make a session without any speaker (it was always intended, it was my PR due to which this flow broke for a while) .
- A session may have no speaker 
- A speaker has to be associated with a session.

Of course, @CosmicCoder96 @shreyanshdwivedi can correct me if I am wrong

**Comment by shreyanshdwivedi** [comment]
I agree with what @uds5501 is stating here.
