### ISSUE TITLE
Offline Tickets to show in sold tickets 

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3070]
**Describe the bug**

Offline Tickets to show in sold tickets 

**To Reproduce**

Steps to reproduce the behaviour:
- Buy any ticket with offline mode of payment.
- The following quantity is not shown in Event Statistics

**Expected behaviour**

Please Consider Placed Tickets as Sold to avoid chaos

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 73.3.0

**Additional context**

Work on it

**Comment by kushthedude** [comment]
@CosmicCoder96 Please transfer it to server

**Comment by uds5501** [comment]
@kushthedude do you mind if I work on this?

**Comment by kushthedude** [comment]
@uds5501 Go on , I will close my server PR

**Comment by kushthedude** [comment]
@pradeepgangwar the issue is not resolved, above pr just explicitly adds the stat rather providing the check .

**Comment by uds5501** [comment]
@kushthedude The scope of this particular issue was to reflect placed orders in sold ticket stats. As far as the checks are concerned, that is a server issue and a new issue should be opened requiring those changes.
As far as FE is concerned and this particular issue is concerned, this issue is solved.
