### ISSUE TITLE
Role invites acceptance breaks in production environment

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#3306]
Transition aborted is thrown, app crashes.

**Comment by kushthedude** [comment]
@CosmicCoder96 I just tried it and I think perhaps, Its due to CSP which we have not yet configured on the FE
![image](https://user-images.githubusercontent.com/44091822/61983461-11768c00-b01e-11e9-8e73-dafb52d8855b.png)

If its the cause, I was thinking to fix it using the `cli-csp module provided by ember-cli` , Should I try?
