### ISSUE TITLE
Implementation of PayTM Payment Gateway

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#3319]
**Is your feature request related to a problem? Please describe.**

This is the frontend part for implementation of PayTM payment gateway focusing on boosting sales in India.

The corresponding server issue is : fossasia/open-event-server#6247

**Comment by ritikamotwani** [comment]
Hi @uds5501 ,
I don't understand the need for PayTM at this stage. The app has some major bugs which should be fixed first. Instead of introducing more and more new features shouldn't the existing things work first.
Also PayTM is not something which is feasible either. Things like Google Pay would make more sense in the later stage.

**Comment by mrsaicharan1** [comment]
@ritikamotwani It was discussed in our last meeting with regards to deliverables. So the thing is that we wanted to go ahead with paytm because of the proper development docs & workflow integration .

In addition, the main thing is that it was also required to work with android apps so as to make it agnostic w.r.t that,
we went with paytm for India. Is that okay? 

https://developers.google.com/pay/india/api/web/create-payment-method

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 regarding last meeting : we settled on google pay right ?
Clarify two things: I’m confused now as to where we stand .

In the weekly meeting did we decide for google Pay. (Yes/No)

And secondly,
‘Required to work with android apps’
Google pay does not support android apps ?

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 
Yes.
It does support it but it would have to be implemented separately for android, not on the server-side.

**Comment by ritikamotwani** [comment]
Hi @mrsaicharan1 
I just asking @uds5501 to fix the bugs assigned to him before jumping to new features.


Further I saw the meeting notes right now and I see you've changed them at 8:46am (IST) today. So, how was it decided in the meeting if you've changed the meeting notes after the meeting. And also as I had seen after the meeting, Google wallet was written there, wasn't it?

**Comment by mrsaicharan1** [comment]
> Hi @mrsaicharan1
> I just asking @uds5501 to fix the bugs assigned to him before jumping to new features.
> 
> Further I saw the meeting notes right now and I see you've changed them at 8:46am (IST) today. So, how was it decided in the meeting if you've changed the meeting notes after the meeting. And also as I had seen after the meeting, Google wallet was written there, wasn't it?

Yes, I had changed it but I meant to say that it was decided in the meeting that payment gateways were one of the deliverables which we had, not that we decided that paytm was finalized.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 @ritikamotwani Can you specify what we could proceed with?

**Comment by kushthedude** [comment]
@mrsaicharan1 @CosmicCoder96  I suggest implementing GPay would suffice as far as android is considered, They can confirm the payment from the default UPI app they are using as done by many Indian apps.

**Comment by mrsaicharan1** [comment]
All the sub-issues have been solved here itself. Closing therefore
