### ISSUE TITLE
Link Explore route to search bar

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#345]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

The explore route is not linked anywhere on the page, has to be accesed manually
**Expected behavior:**

It should be linked to the search icon of the search bar.
![image](https://user-images.githubusercontent.com/17252805/27511046-90f866de-593a-11e7-8fe4-f637145374cc.png)

**Comment by CosmicCoder96** [comment]
@niranjan94 Will the while search input field be a form? (Like on orga server)

**Comment by ritikamotwani** [comment]
@mayank8318 is this issue solved already? Can we close this?

**Comment by pranav1698** [comment]
I think this issue is not resolved I would like to work on this issue

**Comment by niranjan94** [comment]
@pranav1698 this issue is on the development branch. The explore route is at `/explore` as defined here -> https://github.com/fossasia/open-event-frontend/blob/development/app/router.js#L110

**Comment by pranav1698** [comment]
heya @niranjan94, I asked the question because in contrast to the heroku deployed site there is no search bar, 
![screenshot from 2018-10-05 21-33-05](https://user-images.githubusercontent.com/34754265/46546497-d9fbef00-c8e6-11e8-8f5e-c32da647f21b.png)
 
I realized just now that the `/explore` route is set on the `Browse events` button onClick;  as 
![open-event-frontend](https://user-images.githubusercontent.com/34754265/46546778-b6857400-c8e7-11e8-8828-f170f2e05eaa.gif)

So seeking the explore route manually is resolved;  If you to change the way explore route is accessed  
I would be very happy to work on it
