### ISSUE TITLE
Wrong tab highlighted in nav bar at /events/event_id/edit page

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-frontend#386]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

If someone opens `/events/963d3ba5/edit/sessions-speakers` or `/events/963d3ba5/edit/sponsors` directly via URL then the nav bar always points to basic-details tab irrespective of the page opened.

![image](https://user-images.githubusercontent.com/12701036/27726909-ed821b58-5d99-11e7-85e8-b4f82aa00770.png)

**Expected behavior:**

It should point to the correct tab in the navigation bar.

**Steps to reproduce:**

If you open the edit sponsors using the URL `/events/event_id/edit/sessions-speakers`, you wil see the tab `basic-details` will be selected.

I would like to work on this.

**Comment by harshitagupta30** [comment]
@niranjan94 wanted to clarify that what's the reason behind creating the whole edit page using the custom-form-mixin? Also, Is this issue valid? Because when I tried to change the index page route to some other page e.g. sponsors then also it's pointing to the `basic-details` tab which implies not matter what page you open it will go stepwise. Can you please guide? Thanks :)

**Comment by harshitagupta30** [comment]
@niranjan94 Can you please guide?

**Comment by niranjan94** [comment]
@harshitagupta30 just add 

```
    this.notifyPropertyChange('autoSteps');
```

to `didInsertElement` of `components/widgets/steps-indicator.js`

This occurs due to how observables work. An observable is not triggered unless either of the values it is observing changes. So, when the page is opened for the first time, both `session.currentRouteName` and `autoSteps` are constant. So, the observable never executed and default step was `1`. 

So, what `notifyPropertyChange` it tells the observer that the property has changed. So, the observer re-runs and the step is updated.

**Comment by harshitagupta30** [comment]
@niranjan94 Thanks a lot for such brief explanation. :)
