### ISSUE TITLE
website loading speed:

### ISSUE THREAD

**Issue by Ritwik880** [fossasia/open-event-frontend#4476]
**Is your feature request related to a problem? Please describe.**
The website takes approximately 10-11 seconds to load the whole content.

**Describe the solution you'd like**

Minify CSS :
Compacting CSS code can save many bytes of data and speed up downloading, parsing, and execution time.

Avoid CSS @import:
Using CSS @import in an external stylesheet can add additional delays during the loading of a web page.
CSS @import allows stylesheets to import other stylesheets. When CSS @import is used from an external stylesheet, the browser is unable to download the stylesheets in parallel, which adds additional round-trip times to the overall page load.

**Comment by iamareebjamal** [comment]
These are not the reason why site takes a long time to load. The choice of ember JS's way of loading everything on the page upfront instead of asynchronously like every sane JS frontend does, and client side rendering which takes 3X more time than server side rendered pages is the reason for this slow loading speed.

Since, unfortunately, we can't change it to server side rendering, the partial solution that can be achieved is to drop ember's "recommended" way of loading things in a controller/route and move it to individual components

**Comment by mariobehling** [comment]
Closing this as reasons are explained.
