### ISSUE TITLE
Featured events no longer on start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4481]
A number of upcoming events are no longer listed on the start page in the section Upcoming or Featured Events.

![Screenshot from 2020-06-21 06-14-09](https://user-images.githubusercontent.com/1583873/85216612-e9ef8700-b386-11ea-9894-20647f5a1f83.png)

See featured events at https://eventyay.com/admin/events/live

![Screenshot from 2020-06-21 06-13-41](https://user-images.githubusercontent.com/1583873/85216621-fd025700-b386-11ea-932d-fe3c93e9c0aa.png)

**Comment by iamareebjamal** [comment]
This has happened because people registered too many recent events and featured events are filtered from upcoming events and now the furthest upcoming event is in July 30th 2020, so no featured event past that are showed.

1. Featured Events should be queried separately and not just filtered from upcoming events 
2. How should spam events be handled in upcoming events? All these events have tickets. How should they be filtered out? If we only show events from a particular organizer once, then only 1 of our event will be shown.

**Comment by mariobehling** [comment]
Ok, agree to 1.

> How should spam events be handled in upcoming events? 

The idea to only show events with tickets came up because spam events before did not have tickets. Here is another idea: We only show events on the start page in the "Upcoming Events" section that are a) either promoted or b) have sold at least 8 paid tickets using an online payment method (not suitable for offline payments.) What do you think?

**Comment by iamareebjamal** [comment]
Makes sense
