### ISSUE TITLE
Cannot remove or delete custom question

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4596]
In case there is a typo an event an organizer would like to be able to edit the custom form. Also sometimes the organizer tries out this feature and just wants to be able to delete a custom form field as well.

Please provide the option to edit or delete a custom form field.
* In attendee form (Wizard step 2)
* In speaker and session form (Wizard step 5)

![Screenshot from 2020-11-01 10-29-32](https://user-images.githubusercontent.com/1583873/97799295-8c6d2000-1c2d-11eb-96b7-3ac262b26f1d.png)

**Comment by iamareebjamal** [comment]
Before this, we'll need server side checks to ensure no one can delete existing fields. So, only fields which are allowed to be edited and deleted are custom form fields. This is necessary because the pre-existing fields are of a certain type for a reason. If this is too restrictive, then we should allow deletion of non-custom fields if they are not fixed, but allow editing of only custom fields. 

Also, allowing option to delete/edit form fields have potential for data loss as previously submitted forms will now not be shown to the organizer but this is an informed decision for them to be taken and can be shown in a popup before editing/deleting

**Comment by mariobehling** [comment]
Yes, absolutely. We only allow editing of custom fields. We dont allow it for the standard fields. Ultimate goal would be to have it working similar to Google forms, where a user can edit a field without data loss, but of course you cannot delete it and expect the data to stay complete.

**Comment by vikramroy622** [comment]
mai i work on this isue ??

**Comment by iamareebjamal** [comment]
Delete Implementation remaining as it was more involved. For now, organizers can remove the field inclusion which is almost same as deletion

**Comment by maze-runnar** [comment]
trying it.

**Comment by maze-runnar** [comment]
@iamareebjamal, i am asking about an alternate implementation of delete. Click on edit and then remove that field - 
![Screenshot from 2020-09-08 17-27-32](https://user-images.githubusercontent.com/56407566/92473812-bc351400-f1f8-11ea-81dd-176b4ed8ee06.png)

**Comment by maze-runnar** [comment]
I want this kind of logic, it's working with popObject but not with removeObject.
```
@action
  deleteFormField(): void {
    if (!this.validIdentifier) {
      return;
    }
    this.args.customForms.removeObject(this.args.field.fieldIdentifier);
   this.args.isIncluded = False;
    this.args.onSave && this.args.onSave();
  }
```

**Comment by iamareebjamal** [comment]
You have to use `deleteRecord` And you cannot edit args. They are read only
