### ISSUE TITLE
Organizer: Sessions List Page - Make table sortable in all columns and show 25 sessions by default

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4800]
The sessions list page of organizers does not let them sort table rows. It also only shows 10 rows by default, e.g. https://eventyay.com/events/16fa59c7/sessions/all

Please change as follows:
* show 50 sessions by default
* Make the table sortable by
  * [ ] Speakers 
  * [ ] Rating 
  * [ ] Track 
  * [ ] Type 
  * [ ] Submission 
  * [ ] Date 
  * [ ] Last Modified 
  * [ ] Lock Session

**Comment by iamareebjamal** [comment]
> show 50 sessions by default

That'll make the site very slow and also put a huge load on server. There is already an option to choose number of items per page. If important, default can be switched to 20

> Make the table sortable by

speakers, rating, track
These are one-to-one or one-to-many resources linked to a session. Sorting by speaker doesn't translate to anything on the server. For supporting that, we'll have to write custom special query to support sorting by these items and then patch the library code as it itself doesn't allow sorting by anything other than scalar object.

For example, sort by title translates in SQL to `SELECT * FROM SESSIONS ORDER BY TITLE;`

Sorting by speakers would not even be able to easily query, because it'll require join in speakers table, then combining the names of speakers and then sorting on that might be possible. Then which order should speakers be joined? `Areeb Jamal, Mario Behling` will display on top. `Mario Behling, Areeb Jamal` would display on bottom. Similar with track names, however, that might be possible (though not easy). Sorting on non-scalars is too much complexity and little benefit.

It might seem easy because on frontend, it's just a simple string, but not all items are/can be loaded on frontend in one go, hence sorting/filtering on server is needed

**Comment by mariobehling** [comment]
Thanks for outlining what is needed.

Ok, 20 sounds good then, but 25 is currently an option. So, maybe go with that?

Regarding sorting, I think we ultimately need it, but as it requires more effort let's not do it now.
