### ISSUE TITLE
Wizard Step 2: Cannot change first option of social links (website)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5116]
The social links section should 
* allow the first link to change the option from website to something else, e.g. Twitter.
* have the option "Event Site" in the dropdown instead of "External Event URL"

There is no need to have two + buttons.
* A plus button can be anything website or social link. There is no need to distinguish between those.

Also there is an issue if a user chooses two websites: 
* When the user saves the choice and then returns to the social links in the wizard, the website appears as an editable field. 
* Expected: It should be a dropdown item as before.

![Screenshot from 2020-09-21 19-18-33](https://user-images.githubusercontent.com/1583873/93799372-5fe1e380-fc3f-11ea-9534-4a5b2a982a0a.png)

**Comment by shivalikadevi** [comment]
i want to work on this issue

**Comment by max-keviv** [comment]
@mariobehling  can i get the link to that section

**Comment by mariobehling** [comment]
There are some more details to this issue. I added them in the description. Thank you.

**Comment by iamareebjamal** [comment]
@mariobehling I have almost completed the new implementation of link input and while finalizing, I understood the issue again and realized that first option cannot be changed because it is not a social link.

So, there are 2 different things:
1. Event Site/External URL - This is static and cannot have more than 1 site. And cannot be removed, but can be set to empty/null
2. Social Media Links - These are dynamic and can be added and removed and can have 0 or more than one entries

The first option is not a dropdown because it is not a social media link but external event URL, it cannot take twitter, etc as an input.

So really what should be done is that there should be a different section for social media links below and this field should be more clearly specified that it is for external event website

**Comment by mariobehling** [comment]
@iamareebjamal The request of organizers for this feature is as follows:

1. They want to have a freely editable "Field Name" (e.g. Website, Event Website, Company Name or whatever and the link) 
2. They want to have an option to add Social Links (can we have a choice of more social networks that we did not cover before as well please)

In a perfect world we could handle this in the same way that Google handles it in their contact form. If not please make two different forms.

Please do not delete the "WWW" if users enter it.

**Comment by iamareebjamal** [comment]
1. We can have this if we just remove the field for event site/external even URL and just treat custom links as the source of truth for any website or social media. We had external event URL for specifically redirecting users to the site if they had ticketing somewhere else. Now that we don't have the option of making ticketing optional, we can just show the links form without event site field. The disadvantage is that if we only show custom links and it to be freely editable, we will not be able to know what is event site in the future if we need it for special purpose as we will not be able to differentiate it from other custom/social links. Google Forms doesn't have this issue because it neither cares about nor processes the data submitted except to expect it in a certain format or to be used for special purposes. 
Secondly, we can either make the field freely editable or a dropdown. I don't know how we could do both. This is why 2 buttons were added, one for freely editable custom link and other for social media. As you wrote in the issue itself, it is confusing because reloading the page makes it editable field and someone might expect it to be dropdown. So what should we do here, we either provide dropdown or editable field?

2. Yes we can add more social networks

**Comment by mariobehling** [comment]
Yes, just proceed as you described, please. I don't see we need external event URL anymore (at least not here).

So, two separate sections a) Custom Links and b) Social Links seem fine.

**Comment by iamareebjamal** [comment]
Great
