### ISSUE TITLE
Donation Ticket: Error Message missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5169]
After the recent PR there is no error message any longer as expected. Below is a screenshot how it was before (even though the message appears with the wrong numbers). However now the error message does not appear anymore

![Screen Shot 2020-06-17 at 16 02 03](https://user-images.githubusercontent.com/32028823/84878502-1ddf5980-b0b4-11ea-9499-3b370feedef0.png)

**Comment by mariobehling** [comment]
![Screenshot from 2020-09-28 17-44-11](https://user-images.githubusercontent.com/1583873/94454955-d4be9b80-01b2-11eb-826d-a96320a211c7.png)

When the second number is lower than the first one there should be an error message.

**Comment by iamareebjamal** [comment]
@maze-runnar Please take this up on priority. If this can't be solved, let's revert the PR for now

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
the problem is not only in the donation ticket section, this is also in `Number of tickets allowed per order`. The validation function some time works, some time doesn't and sometimes wrong.
![Screenshot from 2020-09-29 09-56-14](https://user-images.githubusercontent.com/56407566/94512696-4b52ac00-023a-11eb-95cf-adde4384be05.png)
![Screenshot from 2020-09-29 09-56-00](https://user-images.githubusercontent.com/56407566/94512702-4e4d9c80-023a-11eb-8c77-3cce38309010.png)

**Comment by iamareebjamal** [comment]
Yes this was the original issue with the previous issue as well. jquery dynamic validation just isn't good. And it is coupled so much with form components that it is impossible to migrate it step by step. Reverting the PR for now to revisit later
