### ISSUE TITLE
Event description loses links, line breaks...

### ISSUE THREAD

**Issue by datapythonista** [fossasia/open-event-frontend#5178]
I created an event with links, line breaks... The event description edition provides buttons to add those, so they should be supported. But once I save the event, the links are lost. And when I view the event, the line breaks are not respected, and all the texts are shown one next to the other, in a single paragraph.

**Comment by iamareebjamal** [comment]
Links were not lost when I tried but line breaks were stripped. So I have fixed that in the above PR

**Comment by iamareebjamal** [comment]
Example event with links and line breaks https://open-event-frontend-czssukq39.vercel.app/e/295ce8c5

**Comment by datapythonista** [comment]
If you write a link, they become links. But if you add a link with the link button, and the text is not the link itself, then they get lost.

**Comment by iamareebjamal** [comment]
Yes, that is not intended to be text AFAIK, the textbox only takes a link for now.

**Comment by mariobehling** [comment]
So, the issue is this: When the organizers uses the link button feature and creates a link, then saves the event and then opens the public page, the link is not there.

Also when the organizers edits the event again the entered link disappeared.

![Screenshot from 2020-09-29 22-57-46](https://user-images.githubusercontent.com/1583873/94615051-64457680-02a7-11eb-8574-46e85ce40d31.png)
