### ISSUE TITLE
Send email to attendees

### ISSUE THREAD

**Issue by datapythonista** [fossasia/open-event-frontend#5200]
I've been looking for a way to send an email with information to the attendees of my event, and I couldn't find it. Is this not implemented? Seems like a very basic feature to me.

**Comment by mariobehling** [comment]
Thank you. This feature is not on our roadmap currently. The reason is, that we want to focus on event management instead of mailing. We provide all the attendee data to the organizer though.

The truth is that people nowadays often say they did not receive a mail, it is in Spam etc. So, rather than focusing on providing email services which could require a support team, we focus on event management services (even though we of course still provide the necessary system emails).

Also in contrast to e.g. Meetup.com we do provide all data including email addresses of an event to organizers. Simply go to your event dashboard > Tickets > Attendees or Orders > on the top right there is an export button. We recommend to use the CSV export as it is much faster than PDF export generation. An enhancement we will provide in the near future is a download link.

That way you have all the data and you can use the email or contact method that you like. Hope this helps.

![Screenshot from 2020-09-30 17-54-30](https://user-images.githubusercontent.com/1583873/94710108-bd181c00-0346-11eb-98cb-529e12eb7239.png)

Closing this as it is currently defined out of scope. Thank you.

**Comment by datapythonista** [comment]
Exporting the data is very useful. Would be convenient to be able to send reminders, event instructions... to attendees, but thanks for the quick answer, I'll send a regular email.
