### ISSUE TITLE
Ticket Order: If there is only one ticket type, please pre-select '1' instead of '0' 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5449]
If there is only one ticket type, please pre-select 1 instead of 0. If there are more ticket types please leave the implementation as is for this case.

Compare https://eventyay.com/e/1f720482
![Screenshot from 2020-11-02 12-11-10](https://user-images.githubusercontent.com/1583873/97861908-cd843380-1d04-11eb-932e-b87e2f632ce1.png)

**Comment by daretobedifferent18** [comment]
I am working on this issue.

**Comment by daretobedifferent18** [comment]
@mariobehling @iamareebjamal I have a question. What if there are only one type of tickets for an event and eventOrganizer have manually selected that minOrder for that event is for e.g. '3' then I think per-selecting '3' tickets instead of 1 would be better.
So what I conclude is that if there are only type of tickets then instaed of pre-selecting '1' we should select minOrder.
What do you say on this?

**Comment by iamareebjamal** [comment]
Correct
