### ISSUE TITLE
Simplify registration process

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5469]
Our current registration process is that ticket buyers need to add a password during the first registration and then confirm their email address through a link in the welcome mail.

How can we make it even easier to go the first steps? We want users to use the system as quickly as possible. So, we can move the "set password" to the step after they confirm their email address.

Please implement a process as follows:

1. User signs up or gets a ticket and signs up.
2. As of now we require users to insert their email. Then we check if the account exists. If the account does not exist, let the user continues to sign up or buys the ticket without password. They should simply add their Email or when they buy a ticket add whatever is needed to get the ticket.
3. The user receives a welcome email with a confirmation link verifying the email.
4. User clicks the link.
5. User gets to a page: "Thank you for confirming your email! Please set a password for your account." So, instead of setting the password when they first register, the user has to set the password when they verify.
6. The user is logged in right away. (no need to log in again after setting the password)

The advantage of this process is that the user can start to use the page more quickly.

**Comment by iamareebjamal** [comment]
This is easier for the user but incredibly difficult to implement on the backend because now we have multiple endpoints after email verification.

When we send users a verification email, It is a link to the verify page like `/verify?token=<token>`. The frontend doesn't know anything about the user or where it is to go after verification.

After verification, if we want to redirect to set password, we need two things:

1. We need to know and encode this information in the verification link that user needs to go to set password after verififcation. This again means separating the logic from normal registration and order registration as it was previously. As we have noticed, every branch from normal behaviour may contain its own bug and remains largely untested and can result in divergent behavioural changes. Like users receiving different mails from normal, etc. Neverthless, despite that, we have to save in the DB that this is a special case (which we already are because of previous implementation) and then special case it in the verify link and add a bit asking the frontend to redirect to set password. This step is still simpler to implement.
2. The next thing we need to do is to encode yet another token in the email verification link, that is set password. Because the verification token is different than reset password, we need to include that in the verification link as well as the frontend won't be able to do anything with just a redirection. So it complicates the verification link part twofold

So, while it is indeed simpler for user to not fill password in 2 fields while registering, but much more difficult for us to maintain the feature of deferring that field after the registration. And I'm not sure I have seen this feature in any other site.

**Comment by mariobehling** [comment]
As discussed it is out of scope.
