### ISSUE TITLE
Docs: Add screenshot of ASCI in Readme to /docs/images folder and add it in Readme

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5509]
The Readme files shows an image that is hosted outside of the repository. Please add the image into the docs/images folder and add it into the Readme instead of the current image.

![Screenshot from 2020-11-06 15-55-14](https://user-images.githubusercontent.com/1583873/98380290-a8672c00-2048-11eb-907d-6e3247e821bf.png)

**Comment by Raunaksingh100** [comment]
Working on this issue

**Comment by Raunaksingh100** [comment]
@mariobehling @iamareebjamal can you tell me what image is need to add in ### docs/images folder so then i add in readme file 

i am little confused

**Comment by iamareebjamal** [comment]
@mariobehling It's an autogenerated thumbnail of the linked videowhich we'll have to update every time we change the video. For example, we also don't store badges like [![Build Status](https://travis-ci.org/fossasia/open-event-frontend.svg?branch=development)](https://travis-ci.org/fossasia/open-event-frontend) and [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy)
 in the repo as well. They are stored out of the repo as well

**Comment by mariobehling** [comment]
@iamareebjamal Actually, do we need that screenshot at all? This will share data with any service that is connected. Also when we deploy to Heroku. The button should probably be substituted. Our goal: Only load the absolute necessary.

**Comment by anjali1102** [comment]
Is this issue being claimed? Can I claim it now

**Comment by Raunaksingh100** [comment]
@anjali1102 i already fixed and create a pr for this plz find some other issue

**Comment by iamareebjamal** [comment]
If we don't show the screenshot, people will probably not click on it or realize that it is a video. 

> This will share data with any service that is connected

That is only true for services like google/facebook who put tracking cookies on sites and track them across pages. A site cannot access data from other site, just the cookies they have put and that is true for even a link. So, for example, if we put a link to the site, and a user clicks on it, they get the cookies they set to login the user. This is still not the data from other site, but their site only. 
And asciinema is an open source and an standard way of sharing terminal recordings. They are no different in principle that https://shields.io which we use to show the badges.

Secondly, they don't receive that data from the image at all because GitHub knows about the privacy issues and replaces it with a GitHub CDN image link - https://camo.githubusercontent.com/44e0f415fd21c8e3282d64f2feea2602862975d6/68747470733a2f2f61736369696e656d612e6f72672f612f3337303435382e706e67
So the data issues don't apply to GitHub linked images. Because adding an external images to GitHub and putting them in docs folder have no difference because they are both served by GitHub only. It just makes maintenance a bit more difficult.

If we are removing the screenshot, we might as well remove the video because people couldn't be bothered to click the link to instructions anyway and got the same errors always.

**Comment by mariobehling** [comment]
Ok, agree. Let's not get rid of an image here. Substituting an image with a local image seems like a good intermediary solution to me, so we do not have to depend on GitHub to make things anonymous for us in the future.

Embedding an image means services receive the IP address and other info of a user. This is different to a link where a user clicks actively. Right now we use Github. We dont know if this stays like that. What happened to youtube-dl makes us aware that we should not depend on GitHub always, especially when they anonymize things for us here. This is the similar to just adding a screenshot to Youtube instead of embedding Youtube.

So, adding a kind of screenshot seems like a good thing here. And we also need to substitute some badges like shields.io, but that is not part of this issue.
