### ISSUE TITLE
Improve Site Speed: Preload key requests

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5572]
According to the Google Page Speed test https://developers.google.com/speed/pagespeed/insights/?url=eventyay.com preloading key requests could improve the speed by 6 seconds. Please improve the speed by implementing the recommended changes as outlined in this article https://web.dev/uses-rel-preload/.

![Screenshot from 2020-11-11 10-36-43](https://user-images.githubusercontent.com/1583873/98794980-f940a100-2409-11eb-89c3-bdcb3c5f1e66.png)

**Comment by iamareebjamal** [comment]
Same problem as #5575
Secondly preload works good for prerendered and pregenerated (server side rendered pages) because browser - can see the resources and download them while rest of the stuff is loading. Because our page is rendered using JS, the resources needed to be loaded on a page is dynamic and cannot be preloaded. Even if there was a way to add preload tags when the javascript runs, it will be of little to no use because the browser would be loading that resource by then anyway.
Secondly, webpack/rollup is the only way to defined preload tags dynamically with route based splitting, which we can't do, cause ember...

**Comment by Raunaksingh100** [comment]
i am working on this issue

**Comment by Raunaksingh100** [comment]
i am working on this
