### ISSUE TITLE
Translations: Make all areas translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5609]
It seems some areas in the system are not translatable yet. Please make all areas translatable. Below a list of areas I identified as currently not translatable:

* All Tables
   * Dashboard
   * Speakers
   * Sessions and session filters
   * Session columns: Accepted and other statuses
   * Admin sections

* Wizard: 
   * Location/Online
   * Dropdown event types etc.
   * Custom Attendee Form fields
   * Publication sentence on wizard bottom
   * Speaker and Session form

Frontpage and Search
   * Tags
   * Filters

Ticket
* Ticket PDF

A few relevant screenshots:

![Screenshot from 2020-11-13 15-21-39](https://user-images.githubusercontent.com/1583873/99082131-0c976c00-25c4-11eb-9153-faa7e98f68ef.png)
![Screenshot from 2020-11-13 15-20-44](https://user-images.githubusercontent.com/1583873/99082135-0dc89900-25c4-11eb-9c58-12445bb94aaa.png)

![Screenshot from 2020-11-12 14-24-26](https://user-images.githubusercontent.com/1583873/99081771-98f55f00-25c3-11eb-8dc5-3b9317c9e70b.png)
![Screenshot from 2020-11-13 15-11-43](https://user-images.githubusercontent.com/1583873/99081614-664b6680-25c3-11eb-9cee-e04e80a55784.png)
![Screenshot from 2020-11-13 15-10-53](https://user-images.githubusercontent.com/1583873/99081619-677c9380-25c3-11eb-832d-dc9e160adb5a.png)
![Screenshot from 2020-11-13 15-09-13](https://user-images.githubusercontent.com/1583873/99081622-68152a00-25c3-11eb-97f9-c6a805c2ee18.png)
![Screenshot from 2020-11-13 15-08-12](https://user-images.githubusercontent.com/1583873/99081624-68152a00-25c3-11eb-994d-f4368c03469b.png)
![Screenshot from 2020-11-13 15-04-04](https://user-images.githubusercontent.com/1583873/99081626-68adc080-25c3-11eb-9894-e61742154967.png)

**Comment by sachinchauhan2889** [comment]
taking it up

**Comment by iamareebjamal** [comment]
Great job @sachinchauhan2889 We also need to list possible `t-var` values in the component where it is used so it gets extracted in messages.pot

So, let's say that session.state is used in t-var, so in one component, whichever is more prominent, we will list all possible values of session.state, like

`{{t 'Accepted}}` etc

So when we extract messages.pot, it is listed there and can be translated

Now, this is already done for session state because we have a dropdown which lists the values, and hence you can see them translated, but it is not true for other values

**Comment by nayanvayada** [comment]
I wanna work on this issue plz aasign this to me
