### ISSUE TITLE
Wizard Step 5: Page often does not load forms below top area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5768]
The wizard step 5 often has problems loading content below the first section. It loads the top area and then loads the footer. All forms in-between do not show up. 

This happens possibly when Internet connection is not very fast or if there are a number of sessions and rooms added. Hard-refreshing the page solves the problem, but even if the user refreshes the system it sometimes only loads the top area. This problem seems to be appearing since the redesign of the Call for Speakers area which can now be activated or deactivated.

![Screenshot from 2020-11-25 23-25-55](https://user-images.githubusercontent.com/1583873/100288156-5bef7c00-2f76-11eb-9057-77c7e774406a.png)

**Comment by hpdang** [comment]
I experienced similar issue. And when I clicked on the "+" sign to add a new track, room, or session, it took a long time before the new field appeared and sometimes it didn't appear until I clicked the Save button. For some reasons it ran very slowly in the back

**Comment by iamareebjamal** [comment]
The issue is there since last release as well, so not related to new changes. The reason is that the forms on this page are very complex (calendar and wysihtml) and ember renders them synchronously, so till each and every component is initialized and all callbacks are settled, only then it is visible to the user, so it can take 4-5 seconds. I searched a lot but couldn't find any way of deferring rendering in ember. Leaving others to have a go at it

**Comment by mariobehling** [comment]
In that case I wonder if we need to split the form. However, from the logic things somehow belong together I think.

**Comment by iamareebjamal** [comment]
I think just delaying rendering of stuff for 500-600 ms will work

**Comment by mariobehling** [comment]
ok

**Comment by maze-runnar** [comment]
looking into it

**Comment by maze-runnar** [comment]
the problem is happening due to `TypeError: Cannot read property 'announcement' of null`. Sometimes 
`Uncaught Error Class : Ember Data Request GET http://127.0.0.1:5000/v1/events/2/speakers-call returned a 404` happens then the below and the CFS part doesn't loads. Other times the problem is not there.
![Screenshot from 2020-11-28 17-24-57](https://user-images.githubusercontent.com/56407566/100514928-ac492280-319e-11eb-9fdf-bf6d0f414b42.png)

**Comment by maze-runnar** [comment]
I put a condition over that section like` {{#if this.data.speakersCall}}` and now the whole page is loading in every situation, every time , but when previously the whole below section disappered ,now renders correctly, but without cfs section - 
![Screenshot from 2020-11-28 17-37-05](https://user-images.githubusercontent.com/56407566/100515251-b0763f80-31a0-11eb-97a0-12e53ae7dbee.png)

**Comment by maze-runnar** [comment]
const speakersCallPromise = this.getOrCreate(data.event, 'speakersCall', 'speakers-call');

the problem is in getOrCreate because, it is used with cfs and copyright only and both two shows same error - 
Copyroght too `Ember Data Request GET http://127.0.0.1:5000/v1/events/2/event-copyright returned a 404↵`

![Screenshot from 2020-11-28 17-47-37](https://user-images.githubusercontent.com/56407566/100515385-d223f680-31a1-11eb-8932-fc9e466f2c15.png)
