### ISSUE TITLE
Public Schedule Social Links: Create a CSS icon for Event Site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5824]
As a follow up to PR https://github.com/fossasia/open-event-frontend/pull/5812 the event site link is the only link without an icon. 

Please create an icon using CSS. 

An example icon is below:

![bitmap](https://user-images.githubusercontent.com/1583873/100542535-c3dde500-324a-11eb-8a80-0f38b6292353.png)

It should be positioned with those other icons.
![](https://user-images.githubusercontent.com/72552281/100519805-305fd200-31c0-11eb-94d9-04dd62ef2dcf.png)

**Comment by palakshivlani-11** [comment]
I wanna take up this issue.

**Comment by AdityaArunSharma** [comment]
@mariobehling is this issue open? Can i take it?

**Comment by iamareebjamal** [comment]
Take one issue at a time

**Comment by Abhijay007** [comment]
can you please tell me what is the name of that font mentioned in the above logo?

**Comment by Abhijay007** [comment]
@iamareebjamal Sir, I made this logo and have its CSS code as well 
![event](https://user-images.githubusercontent.com/64387054/100728479-9b422080-33ed-11eb-8a4a-e4b7190189cd.PNG)

but I don't know how to insert it in eventyay existing code base because I don't have that much idea of ember js
So, can I make a PR with the coded file?
