### ISSUE TITLE
Wizard Step 2: Adding and removing field again results in "field may not be null"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5855]
On wizard Step 2 adding a social media or extra link field and then removing again during the same edit results in "field may not be null".

Expected: As the field is not required and it was already removed the error should not appear.

Compare https://eventyay.com/events/ae73f280/edit/other-details

![Screenshot from 2020-12-01 21-25-23](https://user-images.githubusercontent.com/1583873/100793111-f68b0780-341b-11eb-8316-c72bc7bbc3b3.png)

**Comment by maze-runnar** [comment]
`{"data":{"attributes":{"name":null,"link":"https://hope.com","identifier":"4ade3dd0-3457-11eb-aa16-3be112e11808"},"relationships":{"event":{"data":{"type":"event","id":"1835"}}},"type":"social-link"}}`

when website is selected in dropdown by default, then name is null, that's why it is showing field may not be null.
