### ISSUE TITLE
Virtual Events: Add autoplay option to vimeo and youtube

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6788]
For virtual events using Vimeo or Youtube video it would be good to have an autoplay option on video editing page as documented here https://vimeo.zendesk.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos.

![Screenshot from 2021-02-21 19-55-17](https://user-images.githubusercontent.com/1583873/108635250-c8e3b680-747e-11eb-8999-10474922c014.png)

**Comment by ranjitkshah** [comment]
@iamareebjamal should i add a column for this? or any other options from frontend

**Comment by maze-runnar** [comment]
@ranjitkshah it can be something like(don't know if it's ok) - when a user select autoplay option, then set url to something like`https://www.youtube.com/watch?v=77RmU8QcM4k&autoplay=1` otherwise ``https://www.youtube.com/watch?v=77RmU8QcM4k&autoplay=0`` and then split url to get ID and autoplay option.

@iamareebjamal is it ok?

**Comment by iamareebjamal** [comment]
No, URL will remain same, use extras column to store this info

**Comment by rohank2502** [comment]
Hey !! Is this Issue Open Still Now I will like to work on it.
