### ISSUE TITLE
Schedule: Date not showing for popularity sorting

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6944]
When the popularity sorting feature was introduced a few days ago the date of a sessions was shown on the lef-hand side and if two or more sessions were within the same date it was grouped. The date has disappeared.

**Comment by iamareebjamal** [comment]
Yes, we cannot support grouping by date unless sessions are sorted by date. It was a bug that sessions were being grouped by date when sorted by popularity and since has been fixed. It is impossible to group sessions by date when sorted by anything other than date, else, they were not shown correctly and sessions with popularity 5 were being shown above popularity 10 because their date was before more popular sessions
