### ISSUE TITLE
Order not possible due to unexpected error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7242]
The ordre of tickets on this event is not possible https://eventyay.com/e/6743ef60

![Screenshot from 2021-05-07 17-04-28](https://user-images.githubusercontent.com/1583873/117469791-65820480-af56-11eb-9f3d-11f621395aef.png)

**Comment by iamdevvalecha** [comment]
![Screenshot from 2021-05-08 13-55-01](https://user-images.githubusercontent.com/71969867/117533578-32e61380-b00b-11eb-939b-a0bb1a52eef0.png)

**Comment by Amit-Morade** [comment]
Can I work on this issue?

**Comment by iamdevvalecha** [comment]
@Amit-Morade yes it's open.

**Comment by naman153** [comment]
Is anyone working on the issue or i can work on this issue?

**Comment by klsingh016** [comment]
Can I work on this issue?

**Comment by maze-runnar** [comment]
on it.

**Comment by sachinchauhan2889** [comment]
@mariobehling @maze-runnar @ranjitkshah @MeghalBisht 

This issue is debugged.

We all know that all characters have their ASCII codes. Example A=97 etc.
So we have ASCII code for `line feed` character as 10, we all know this character as `\n` and `&#010;`
But in our rich text editor whenever we type '\n', it doesn't recognise this as a 'line feed' character. We need to add `<br>` for line break.
We all know this character `\`. This is escape character, this tell language to “not execute the next character”. So our rich text editor adds `\` before every `\` present in editor text.
- Let's take an example:- 
Let's type `hi \ hi \n` in the editor and click the save button. Editor converted this to `hi \\ hi \\n`. It tells us not to execute `\n`. A request is made to the server with `hi \\ hi \\n`. Our server takes this and executes the first `\` not the second one. So in our database `hi \ hi \n` is stored. Remember we have `\\` but first `\` is executed and it says not to execute the next character, and language does not execute the second `\` , in this way we get actual data saved in the database which we see in our rich text editor. 

It is working fine when we type text in the editor.
But most of the time users copy and paste text in the editor. If pasted text contains `line feed` character(not in `\n` form), our editor will not do anything because it will not encounter `\`. So a request is made at the server with `line feed` character, and server stores `line feed` character in the database. So whenever the server uses this data it will execute `line feed` character. 
So when we make a request to place an order. Order is placed. And the server starts preparing a calendar to be sent in email. During making the calendar it takes `owner_description` from the database and this contains `line feed` character and calendar export fails and email also fails and ultimately order fails. Order table gets all data fields filled in its starting steps but in the second last step(email sending) order fails. Hence we will see order in our `my_tickets`. Last step is to set `completed_at` field(it is not set since order fails in the email sending step).

- **Solution**: we check  ASCII code of all characters and whenever we see `ascii code ===10`, just remove this character.
I have updated PR.

It will help you to test this PR.
If you have better approach you can tell.
