### ISSUE TITLE
Setup: get authenticated via google/github/facebook account.

### ISSUE THREAD

**Issue by iamdevvalecha** [fossasia/open-event-frontend#7280]
Get directly access to https://eventyay.com/ using google/github/facebook account. 
![Screenshot from 2021-05-15 05-22-33](https://user-images.githubusercontent.com/71969867/118341696-ade48800-b53d-11eb-81d8-f96555139bc6.png)

**Comment by iamdevvalecha** [comment]
@mariobehling @sachinchauhan2889 @MeghalBisht 
As we are about to shift the project into reactJs did we need this feature?
As we currently use jwt auth in server side.

**Comment by klsingh016** [comment]
@maze-runnar can i work on this

**Comment by klsingh016** [comment]
can i on work ?

**Comment by mariobehling** [comment]
We deleted this feature in the past because
a) The implementations keep changing and we do not have a lot of resources to continuously update these features.
b) It turns out less and less people are using these logins. Especially paying business users do not use these services a lot. 
Therefore closing it.
