### ISSUE TITLE
Microlocation Video Rooms do not show on the event page after creating 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#7392]
**Describe the bug**
Go to Video tab https://eventyay.com/events/75ac7f83/video/all
Create a Microlocation room with BBB 
The room did not show on the list of Videos Room on the side panel 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 18.04, Chrome 
 
**Smartphone (please complete the following information):**

**Additional context**

**Comment by mariobehling** [comment]
This room needs to have a session in it in order to appear. Rooms without sessions do not appear. You need to 1. create sessions, 2. add them into the schedule, 3. publish the schedule. This is not a bug. 

Please change the description on the video page as follows:

Microlocation video rooms are suitable for events with different tracks, rooms and sessions that are listed in a schedule. All microlocations are listed on the event schedule. Note: Microlocations (rooms) are only listed on the video channel list on side panels of online events, if session have been added into the room in the schedule.

![Screenshot from 2021-06-05 09-32-24](https://user-images.githubusercontent.com/1583873/120884027-f513e500-c5e0-11eb-9841-b4127607af1f.png)
