### ISSUE TITLE
Chat not working for some users

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7498]
The chat in events is not working for some users. It shows "Unable to login to chat. Please contact the administrator"

![Screenshot from 2021-06-30 10-58-34](https://user-images.githubusercontent.com/1583873/123932918-34401680-d992-11eb-8292-d5783ebf8560.png)

**Comment by maze-runnar** [comment]
can you please share the link for this event? This error usually appears if rocket chat token is missing.

**Comment by MeghalBisht** [comment]
Steps to reproduce -
1. Add yourself in any chat room. 
2.  Click on your user profile at top left.
3. Go to **My Account** -> **Security** -> **Enable 2 factor authentication via TOTP**
![Screenshot from 2021-07-06 02-03-00](https://user-images.githubusercontent.com/61330148/124515962-4f7dac80-ddfe-11eb-919c-7c2cd20210a7.png)
 
After enabling 2 factor TOTP, if you logout manually from Rocket Chat OR your token expires, you are logged out. Once logged out, the next time if login is attempted, since 2 factor authentication was enabled the login fails.

What could be done?
1. https://developer.rocket.chat/guides/developer/two-factor-authentication
2. Disallow users to use 2 factor authentication via TOTP. (not sure if this can be done)

More info at - https://developer.rocket.chat/api/rest-api/2fa
https://developer.rocket.chat/guides/developer/two-factor-authentication

**Comment by MeghalBisht** [comment]
Could not find any option in UI to reset the TOTP  or email (2FA) code for a particular user.
The only solution was to run a query to update the mongo DB directly.
Hence, solved manually.
