### ISSUE TITLE
Users of existing events are unable to change sessions because of "session may not be null error" or Test Slides instead of Slides shows up without form field

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7735]
1. Users are unable to change sessions. Error message `/data/attributes/slides/0/link: Field may not be null`. But: Slides are not enabled even in the Wizard. Therefore there should be no requirement for slides. This is the case for older existing sessions.
2. Newer events show at points the option "Test Slides" instead of "Slides". It seems this was wrongly implemented. The previous slides solution was implemented with a new solution and the update of the functionality was not done properly.

Please resolve this.

Compare: https://eventyay.com/events/bee2414e/session/7219/edit

![Screenshot from 2021-08-30 05-33-30](https://user-images.githubusercontent.com/1583873/131281573-b0aad3bf-e33d-409d-94de-da3acd558cf4.png)

**Comment by progmatic-99** [comment]
I am working on this.

**Comment by mariobehling** [comment]
When I switch on slides for this event, the slide upload field does not appear neither.

![Screenshot from 2021-08-30 09-50-05](https://user-images.githubusercontent.com/1583873/131305025-344cc204-4a29-4f02-a96b-6b640bc792df.png)

**Comment by mariobehling** [comment]
Newly created sessions do not have this problem. However, for any session where the slide upload field should be visible it is not there.

**Comment by progmatic-99** [comment]
In the event-wizard, instead of `Slides` I get this:
![ss_1630328343](https://user-images.githubusercontent.com/42090582/131342957-e79ede6e-29d3-45de-bdaf-5bf98a987732.png)

In the `session edit section`, when  I change `Test Slide` to `required`:
![ss_1630328282](https://user-images.githubusercontent.com/42090582/131343071-b3e6991f-6736-4778-8dd7-11bd6e2d54d5.png)

**Comment by AbhishekJamhoriya** [comment]
@mariobehling can i work on this issue.

**Comment by mariobehling** [comment]
Please join the weekly meeting to discuss this.

**Comment by mariobehling** [comment]
This is related to two PRs where this was changed recently by @ranjitkshah: 1. https://github.com/fossasia/open-event-server/pull/8081 2: https://github.com/fossasia/open-event-frontend/pull/7596

**Comment by progmatic-99** [comment]
As the migration in this [PR](https://github.com/fossasia/open-event-server/pull/8081) wasn't done properly or the `slides_url` was not removed, as it still appears in a lot of places in the backend. Due to that `Slides` is appearing `Test Slide` in **sessions-speakers form**, so we have two solutions:-
+ Redo the migrations and remove slides_url from everywhere in the code, which can introduce  a lot of other bugs.
+ Implement a workaround so that users are able to upload the slides, but the name will remain `Test Slide`.
