### ISSUE TITLE
Empty error box appears during registration process

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7779]
When ordering a ticket using the registration option an empty red error box appears during the order process on the bottom right. It appears even if there is no error.

![Screenshot from 2021-09-13 11-03-35](https://user-images.githubusercontent.com/1583873/133056130-c4592c09-4d5e-4eef-8e5a-3cbe7fa48281.png)

**Comment by daretobedifferent18** [comment]
working on it

**Comment by daretobedifferent18** [comment]
@mariobehling this is coming because the box that should have been printed is e.response.errors[0].detail but when this error is thrown e.response is null which is the reason this box appears to be empty.
![Screenshot from 2021-09-13 21-06-55](https://user-images.githubusercontent.com/71120226/133117185-3b6fdd84-28f7-41af-ba7a-5666795c53a6.png)
