### ISSUE TITLE
Tax is not being calculated properly while ordering tickets

### ISSUE THREAD

**Issue by pc-beast** [fossasia/open-event-frontend#7835]
**Describe the bug**
If we buy paid tickets of more than one type, the tax on orders page shows 0.00 for all tickets. There is probably some calculation issue in tax system.

![Screenshot from 2021-09-21 19-35-25](https://user-images.githubusercontent.com/56963647/134191387-669d99c2-3542-42b7-ad24-418a7dd8507a.jpg)

**Comment by daretobedifferent18** [comment]
working on it

**Comment by daretobedifferent18** [comment]
working on it

**Comment by mariobehling** [comment]
Not yet solved. Compare to https://test.eventyay.com/e/554ef820

**Comment by daretobedifferent18** [comment]
@mariobehling This porblem is not showing on localsystem.
I think there is some problem in new changes been merges not properly deplying or maybe not deployed to 
https://eventyay.com/

bcz the changes made in PR #3820 is also not showing (below ScreenShot).
![Screenshot from 2021-09-23 11-12-11](https://user-images.githubusercontent.com/71120226/134459583-75f5d42b-796d-4840-ad21-daf93d17cda8.png)

I think the problem is in deployment and same goes with this PR.
@maze-runnar pls have a look at this problem

**Comment by mariobehling** [comment]
Still missing the currencies, e.g. USD, Euro, INR in the tax area, but the calculation works!

![Screenshot from 2021-09-23 15-55-51](https://user-images.githubusercontent.com/1583873/134520506-581075c2-b3a1-4ebb-a93c-a3649b359545.png)
