### ISSUE TITLE
Implement access code API to /tickets/access-codes/create

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#797]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Comment by sumedh123** [comment]
@niranjan94 @geekyd What should be the relationship between marketer and access code? Should it be one one or many one?

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 On the server heroku deployment, I checked the behavior of access code creation:
![access-codes-server](https://user-images.githubusercontent.com/17925669/29958787-17e21980-8f12-11e7-96fb-0d09fd8d7a0b.png)

Even if I create tickets, they are not shown under the 'Select all ticket types', what is the workflow there because if I do the same thing in our new app, my request is failing? Do we have checkboxes there to select the tickets?

**Comment by geekyd** [comment]
@srv-twry Yes, please go ahead.

**Comment by srv-twry** [comment]
@geekyd Getting HTTP 500 on creating Access-code
Added details in the WIP PR.
