### ISSUE TITLE
Tickets do not show up at upcoming or past events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8496]
I got a ticket for the FOSSASIA Summit on the second day. The ticket does not show up on the ticket area https://eventyay.com/my-tickets/upcoming/open

![Screenshot from 2022-04-08 00-30-25](https://user-images.githubusercontent.com/1583873/162330242-75aaea29-15d2-4131-b54d-bd78e57b2971.png)

**Comment by progmatic-99** [comment]
Did you complete the order? If yes, then it should be under the Completed Orders ??
@mariobehling

**Comment by mariobehling** [comment]
It is not on any tab. Order it completed.

**Comment by Harshchourasiya** [comment]
Hello, I'm a new member of the community. When I'm studying the codebase I came across an issue:- when you cancel an order it's not visible in the canceled order tab. I think this issue and the cancel issue are from the same root.
**I am working on this problem**

**Comment by Harshchourasiya** [comment]
I find the problem but As I'm a beginner in open source I'm not able to solve this problem on my own I'm looking for a guide although I can hard code this problem buts its not worth in the big project. This problem is coming from its Backend API. 
Problem in Detail:-
So The problem is that when user cancel the order the order is deleted from the order API from which the data is coming from, because of the its only show the complete order, Not Cancel or Open.
means :-

--> When User open `http://localhost:4200/my-tickets/upcoming/completed` its data comes from `https://test-api.eventyay.com/v1/users/{userId}/orders`
--> When User Cancel the order the its orders data is also removed from the `https://test-api.eventyay.com/v1/users/{userId}/orders` API.

I thought to share screenshots but right now `https://test-api.eventyay.com/` is not working I will edit it later. 
I Don't know much about the backend of this project so I'm asking for a guide to solve this problem If you find any problem in my explanation please do comment.

Thanks

**Comment by fosa-ij** [comment]
@Harshchourasiya are you still working on this issue, I'd like to jump on it

**Comment by mayurstwt** [comment]
qdwqewdq

**Comment by Gauravmauryaios** [comment]
i want to work on this project.

**Comment by fosa-ij** [comment]
okay go ahead

**Comment by mariobehling** [comment]
Issues seems to not appear anymore. Therefore closing it.
