### ISSUE TITLE
Timezone issues after change of winter to summer time in Europe

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8690]
The time is not displayed correctly. When a user creates an event in Berlin Germany, the event uses the winter time. Adding the event to Google calendar will result in the event being in another time than displayed on the website.

Also changing the timezone to GMT+1 suddenly displays GMT-1 on the public event page.

Expected: The timezone of the event should always correspond to the timezone of the event day. If an event is created during when the winter timezone is active but the event itself is on a date when the time is summer timezone the event time should use summer time.

![Screenshot from 2023-05-08 19-32-18](https://user-images.githubusercontent.com/1583873/236813611-85ebb45a-f5d3-41d8-97b0-81505f827839.png)
 

![Screenshot from 2023-05-08 19-32-48](https://user-images.githubusercontent.com/1583873/236813599-fd33f541-bba2-424f-ac5c-ed51b3d3ceda.png)

**Comment by none03003** [comment]
I want to work in this

**Comment by Leslie-Wong-H** [comment]
Root code: https://github1s.com/fossasia/open-event-frontend/blob/development/app/helpers/general-date.js#L33-L34 

![image](https://github.com/fossasia/open-event-frontend/assets/27696701/c515b5ae-f471-4fba-9f2d-42ada3fd84e2)

**Comment by Leslie-Wong-H** [comment]
Similar issue related: https://github.com/moment/moment-timezone/issues/723

![image](https://github.com/fossasia/open-event-frontend/assets/27696701/04f6d4d7-92fe-4ea9-8d4f-9aaac144ab78)

**Comment by Leslie-Wong-H** [comment]
As for the winter time problem. It seems it is caused by the way how Google Calendar (& Outlook as well) treat the UTC time string information together with location/timezone. 

Take this as an example, https://eventyay.com/e/02440ae2 

![image](https://github.com/fossasia/open-event-frontend/assets/27696701/0b590ce3-31f8-4996-ab07-9a4c85800532)

![image](https://github.com/fossasia/open-event-frontend/assets/27696701/97f9c2c9-82ae-4676-b7b2-3aa6cf2ab92a)

The time string got from backend is `
{starts-at:"2023-05-26T16:00:00+00:00", ends-at
: 
"2023-05-27T18:00:00+00:00","timezone
: 
"Europe/Berlin"" }`

![image](https://github.com/fossasia/open-event-frontend/assets/27696701/a43ea98d-a1cc-485d-bfad-3254ae8417ba)


`2023-05-26T16:00:00+00:00` and `2023-05-27T18:00:00+00:00` are rendered as `Friday, 26 May, 2023 5:00 PM` and `Saturday, 27 May, 2023 7:00 PM` by eventyay with this method. 
```js
  let dateTime = moment(params[0]).tz(timezone).format(format);
```
 https://github1s.com/fossasia/open-event-frontend/blob/development/app/helpers/general-date.js#L31-L32

But when it comes to Google Calendar, the URL to create event is like this, https://calendar.google.com/calendar/u/0/r/eventedit?dates=20230526T160000Z/20230527T180000Z&text=Timezone+Test&location=https://eventyay.com/e/02440ae2&ctz=Europe/Berlin. Notice the `dates` parameter and `ctz` parameter. 

Unexpectedly, it shifts the time one hours later, probably because of their design mechanism of Daylights Savings Time. 

![image](https://github.com/fossasia/open-event-frontend/assets/27696701/84aa7f3c-b3af-4c30-8a67-2d15aec0875e)

**Need more elaboration about the underlying behaviors that moment.js handles DST.**

**Comment by Leslie-Wong-H** [comment]
Valuable documentation about Google Calendar URL 

[Calendar URL generator which parameters -Google Calendar Help](https://support.google.com/calendar/thread/128416249/calendar-url-generator-which-parameters?hl=en)

[add-event-to-calendar-docs/services/google.md](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/main/services/google.md)

The source code that eventyay uses to visit Google Calendar: 

https://github.com/fossasia/open-event-frontend/blob/45eec1c3eb1d4983c1d1a74abf09103a32202d15/app/components/public/add-to-calender.ts#L69

**Comment by Leslie-Wong-H** [comment]
Tricky enough. 

![image](https://github.com/fossasia/open-event-frontend/assets/27696701/fd49c54e-0018-43a3-9b4d-3bcacd6bf212)

https://github.com/fossasia/open-event-frontend/blob/45eec1c3eb1d4983c1d1a74abf09103a32202d15/app/components/public/add-to-calender.ts#L55C7-L74

**Comment by Leslie-Wong-H** [comment]
A StackOverflow answer to `Does UTC observe daylight saving time?`:

> No, UTC itself never has DST. It is the constant frame of reference other time zones are expressed relative to.
> 
> From the [Wikipedia UTC page](http://en.wikipedia.org/wiki/Coordinated_Universal_Time):
> 
> > UTC does not change with a change of seasons, but local time or civil time may change if a time zone jurisdiction observes daylight saving time or summer time. For example, UTC is 5 hours ahead of local time on the east coast of the United States during winter, but 4 hours ahead during summer.
> 
> In other words, when a time zone observes DST, its offset from UTC changes when there's a DST transition, but that's that time zone observing DST, not UTC.
> 
> Without knowing much about PHP time zone handling, it seems strange to me that you can specify "with DST" or "without DST" in a conversion - the time zones themselves specify when DST kicks in... it shouldn't have to be something you specify yourself.
> 
https://stackoverflow.com/a/5495816/8808175

Since eventyay seemingly uses server-side UTC-0 time to mark timestamps with timezone, I doubt the feasibility to fix this bug.

**Comment by Leslie-Wong-H** [comment]
Pardon, it should have a workaround.

**Comment by none03003** [comment]
If It's giving timestamp error maybe cause of node is not updated?

**Comment by Leslie-Wong-H** [comment]
> If It's giving timestamp error maybe cause of node is not updated?

Why 'node'? It's the browser environment.

**Comment by none03003** [comment]
I thought hence we are using Google timestamp so there are updated all systems and ours is not so maybe some errors is occurring? And we also got new issue to update node cause some test and function giving errors

**Comment by cweitat** [comment]
@Leslie-Wong-H will you be working on this?

**Comment by Leslie-Wong-H** [comment]
> As for the winter time problem. It seems it is caused by the way how Google Calendar (& Outlook as well) treat the UTC time string information together with location/timezone.
> 
> Take this as an example, https://eventyay.com/e/02440ae2
> 
> ![image](https://user-images.githubusercontent.com/27696701/239686550-0b590ce3-31f8-4996-ab07-9a4c85800532.png)
> 
> ![image](https://user-images.githubusercontent.com/27696701/239686635-97f9c2c9-82ae-4676-b7b2-3aa6cf2ab92a.png)
> 
> The time string got from backend is ` {starts-at:"2023-05-26T16:00:00+00:00", ends-at : "2023-05-27T18:00:00+00:00","timezone : "Europe/Berlin"" }`
> 
> ![image](https://user-images.githubusercontent.com/27696701/239686755-a43ea98d-a1cc-485d-bfad-3254ae8417ba.png)
> 
> `2023-05-26T16:00:00+00:00` and `2023-05-27T18:00:00+00:00` are rendered as `Friday, 26 May, 2023 5:00 PM` and `Saturday, 27 May, 2023 7:00 PM` by eventyay with this method.
> 
> ```js
>   let dateTime = moment(params[0]).tz(timezone).format(format);
> ```
> 
> https://github1s.com/fossasia/open-event-frontend/blob/development/app/helpers/general-date.js#L31-L32
> 
> But when it comes to Google Calendar, the URL to create event is like this, https://calendar.google.com/calendar/u/0/r/eventedit?dates=20230526T160000Z/20230527T180000Z&text=Timezone+Test&location=https://eventyay.com/e/02440ae2&ctz=Europe/Berlin. Notice the `dates` parameter and `ctz` parameter.
> 
> Unexpectedly, it shifts the time one hour later, probably because of their design mechanism of Daylights Savings Time.
> 
> ![image](https://user-images.githubusercontent.com/27696701/239687645-84aa7f3c-b3af-4c30-8a67-2d15aec0875e.png)
> 
> **Need more elaboration about the underlying behaviors that moment.js handles DST.**

The mis-logic of this issue is this way. Referring https://clocks.world/time/germany/berlin/, Since March 26 2023, the CET time that Berlin adopts is 2 hours ahead of UTC0, and the status quo here is that
Design time:  when reading the three input box information to generate a time string, the generated time string **still follows the 1 hours ahead logic, not 2 hours ahead,** from "2023-05-26T17:00:00+01:00" getting "2023-05-26T16:00:00+00:00" when converting back to utc0 string, ironically the wrong string gets rendered correctly at the system run time. Yet when sending information to Google Calendar, they treat "20230526T160000Z" with 2 hours ahead logic concerning CET/Berlin, therefore comes an unexpected mismatch. The other Calendars iCal, Yahoo, Outlook may also render wrong results accordingly. 

Inspiration: Find the core code that eventyay uses to generate event time string to post to server and use the DST-safe [Temporal Polyfill](https://www.npmjs.com/package/@js-temporal/polyfill) to ensure the utc0 correctness. Or figure out why moment-timezone is not handling utc0 correctly.
