### ISSUE TITLE
Avoid Greenkeeper.io opening new branches

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#996]
Greenkeeper.io is opening new branches when there is a package update. These branches do not get reviewed as people are missing them. Is there an alternative way?

**Comment by CosmicCoder96** [comment]
@mariobehling The new packages can sometimes break the build or some functionality, that's why @niranjan94 always advised to test them out thoroughly before merging them. Earlier they had to be deployed manually (by @niranjan94 ) but since they are automatically deployed now as soon as they are created, it's no longer difficult to review them.  We merged 8 or 9 of them recently and greenkeeper bot takes care of deleting them  after the merge. Just my view. :)

**Comment by harsh-98** [comment]
@CosmicCoder96 If greenkeeper opens a new branch does that means, if someone makes a PR then that code is tested  by greenkeeper by  making a new branch on the open-event-frintend repo and when branch merges, it also handles its deletion.

**Comment by CosmicCoder96** [comment]
@harsh-98 GreenKeeper doesn't test anything, it just keeps track of various dependencies and makes a PR from time to time when a new version of a dependency is released :)

**Comment by CosmicCoder96** [comment]
@niranjan94 Can we close this?
